# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m8xQ61VK6Or0b76minj9ZKKlrAo74jZ8
"""

import nltk
import random
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('punkt')

knowledge_base = {
    "what is ai": "Artificial Intelligence is the simulation of human intelligence by machines.",
    "what is machine learning": "Machine Learning is a subset of AI that allows systems to learn from data.",
    "what is python": "Python is a popular programming language used for AI, data science, and web development.",
    "what is chatbot": "A chatbot is an AI program that interacts with users using text or voice.",
    "what is ibm skillsbuild": "IBM SkillsBuild is a free learning platform that helps students build job-ready skills.",
    "bye": "Goodbye! Have a great day.",
    "hello": "Hello! How can I help you today?"
}

questions = list(knowledge_base.keys())

def chatbot_response(user_input):
    user_input = user_input.lower()

    vectorizer = CountVectorizer().fit_transform(questions + [user_input])
    vectors = vectorizer.toarray()

    similarity = cosine_similarity([vectors[-1]], vectors[:-1])
    index = similarity.argmax()

    if similarity[0][index] > 0.3:
        return knowledge_base[questions[index]]
    else:
        return "Sorry, I don't understand that yet. Please try asking something else."

print("AI Chatbot is running (type 'bye' to exit)")

while True:
    user_input = input("You: ")

    if user_input.lower() == "bye":
        print("Bot:", knowledge_base["bye"])
        break

    response = chatbot_response(user_input)
    print("Bot:", response)